---
title: "Predicting the Minimum Linear Distance from a Given Pine Tree to the Nearest Tree that is Infected by Pine Beetles"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    theme: yeti
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(GGally) # ggpairs
library(vip)
library(tidymodels)
```

Read Me
==============================================================================

Column {data-width=350}
-----------------------------------------------------------------------

### What are Pine Beetles? And Why Are You Reading This?

Read me before proceeding to the analysis!
(Here goes the objectives for the analysis and a brief description of the problem Pine Beetles pose as well as what they are)


### Relevant habits that might be relevant to our analysis

1. There are multiple organisms that may cause tree death around pine beetles<sup>1</sup>
2. Female Pine Beetles use pheromones to attract other Pine Beetles nearby when they are ready to lay eggs<sup>1</sup>
3. Pine Beetles infestations in forests are usually directional<sup>1</sup>
4. Most Pine Beetles like attacking bigger trees (>10in), but when there is a lot of competition for trees, they will attack smaller trees<sup>2</sup>

5. Pine Beetles usually fly 300 feet or less at a time
- 300 feet = ~.007 acres, which means that we will probably not want to use any of the beetle population pressure measures of over the smallest variable measure (1/20 acres = .05 acres)<sup>2</sup>

[1](https://www.treefarmsystem.org/SPBwhenbeetlesattack)
[2](https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5304956.pdf)
[3](https://fennerschool-associated.anu.edu.au/mensuration/density.html)

Column {data-width=650}
-----------------------------------------------------------------------

### Picture of variables


Data Exploration
==============================================================================

Column {data-width=300}
-----------------------------------------------------------------------

### Data Table

```{r readindata}
pine_tbl <- read_excel("../../hgen-612_temp/p1/data/Data_1993.xlsx", sheet = 1)
```

```{r makeshowcasebones}
glimpse(pine_tbl) # correlation matrix or ggpairs, make a table
```

```{r ggpairs}
# correlation matrix or ggpairs, make a table
```

Column {data-width=450}
-----------------------------------------------------------------------

### GGPairs

```{r ggpairs}
```

### Things to Note


Look at patterns, outliers, anything surprising, reasons for choosing certain 
variables in the recipe, things that are not normally distributed, etc. 

Modelling Strategy
==============================================================================

Column {data-width=350}
-----------------------------------------------------------------------

### Predictors

```{r}

```

### Explanation of code

```{r}

```

Conclusion
==============================================================================

### Model Results

```{r}

```

### ROC AUC

```{r}

```